#!/usr/bin/env bash
# ============================================================================
# GEOFF Installer — Git-backed Evidence Operations Forensic Framework
# ============================================================================
# Usage:
#   curl -sSL https://raw.githubusercontent.com/legacyboy/Geoff/main/install.sh | bash
#   curl -sSL https://raw.githubusercontent.com/legacyboy/Geoff/main/install.sh | bash -s -- --profile local
#   curl -sSL https://raw.githubusercontent.com/legacyboy/Geoff/main/install.sh | bash -s -- --profile cloud --dir /opt/geoff
#
# Options:
#   --profile cloud|local   Model profile (default: cloud)
#   --dir <path>            Install directory (default: /opt/geoff)
#   --skip-ollama           Skip Ollama model pulls (Ollama itself is always installed if missing)
#   --skip-deps             Skip apt dependency installs
#   -h, --help              Show this help
# ============================================================================

set -euo pipefail

REPO="https://github.com/legacyboy/Geoff.git"
INSTALL_DIR="/opt/geoff"
PROFILE="cloud"
SKIP_OLLAMA=false
SKIP_DEPS=false

# ── Colors ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

info()  { echo -e "${BLUE}[GEOFF]${NC} $*"; }
ok()    { echo -e "${GREEN}[GEOFF]${NC} $*"; }
warn()  { echo -e "${YELLOW}[GEOFF]${NC} $*"; }
fail()  { echo -e "${RED}[GEOFF]${NC} $*" >&2; exit 1; }

# ── Parse args ──────────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
    case "$1" in
        --profile)  PROFILE="$2"; shift 2;;
        --dir)      INSTALL_DIR="$2"; shift 2;;
        --skip-ollama) SKIP_OLLAMA=true; shift;;
        --skip-deps)   SKIP_DEPS=true; shift;;
        -h|--help)
            head -14 "$0" | tail -10 | sed 's/^# //'
            exit 0
            ;;
        *) fail "Unknown option: $1";;
    esac
done

# ── Validate profile ───────────────────────────────────────────────────────
if [[ "$PROFILE" != "cloud" && "$PROFILE" != "local" ]]; then
    fail "Unknown profile '$PROFILE'. Must be 'cloud' or 'local'."
fi

info "Installing GEOFF with profile: ${YELLOW}${PROFILE}${NC}"
info "Install directory: ${INSTALL_DIR}"

# ── Check prerequisites ────────────────────────────────────────────────────
command -v git >/dev/null  || fail "git is required but not found"
command -v python3 >/dev/null || fail "python3 is required but not found"

# ── Install system dependencies ─────────────────────────────────────────────
if [[ "$SKIP_DEPS" == false ]]; then
    info "Installing system dependencies..."
    if command -v apt-get >/dev/null; then
        sudo apt-get update -qq
        sudo apt-get install -y -qq python3-pip python3-venv git curl jq \
            sleuthkit volatility3 yara ssdeep hashdeep exiftool plaso-tools \
            regripper tshark 2>/dev/null || true
        # REMnux tools (install if on REMnux or SIFT with REMnux repo)
        sudo apt-get install -y -qq die peframe upx clamav radare2 floss 2>/dev/null || true
    elif command -v dnf >/dev/null; then
        sudo dnf install -y python3-pip git curl jq 2>/dev/null || true
    elif command -v yum >/dev/null; then
        sudo yum install -y python3-pip git curl jq 2>/dev/null || true
    fi
    ok "System dependencies installed"
fi

# ── Clone repo ──────────────────────────────────────────────────────────────
if [[ -d "${INSTALL_DIR}/.git" ]]; then
    info "Updating existing GEOFF installation..."
    cd "$INSTALL_DIR"
    git pull origin main || warn "Git pull failed — continuing with existing code"
else
    info "Cloning GEOFF repository..."
    git clone "$REPO" "$INSTALL_DIR"
    cd "$INSTALL_DIR"
fi
ok "Code ready at ${INSTALL_DIR}"

# ── Python virtual environment ─────────────────────────────────────────────
info "Setting up Python environment..."
python3 -m venv "${INSTALL_DIR}/venv" 2>/dev/null || true
source "${INSTALL_DIR}/venv/bin/activate"
pip install --quiet -r requirements.txt 2>/dev/null || pip install --quiet flask requests jsonschema
ok "Python environment ready"

# ── Configure profile ──────────────────────────────────────────────────────
info "Configuring profile: ${PROFILE}"

# Create .env file for the profile
cat > "${INSTALL_DIR}/.env" << EOF
# GEOFF Configuration — generated by install.sh
# Override individual models with GEOFF_MANAGER_MODEL, GEOFF_FORENSICATOR_MODEL, GEOFF_CRITIC_MODEL
GEOFF_PROFILE=${PROFILE}
OLLAMA_URL=http://localhost:11434
EOF

ok "Profile '${PROFILE}' configured in ${INSTALL_DIR}/.env"

# ── Install Ollama if missing ──────────────────────────────────────────
if ! command -v ollama >/dev/null 2>&1; then
    info "Ollama not found — installing..."
    curl -fsSL https://ollama.com/install.sh | sh || fail "Ollama install failed. Install manually: https://ollama.com"
    ok "Ollama installed"
fi

# ── Ensure Ollama is running ──────────────────────────────────────────────
if ! curl -s http://localhost:11434/api/tags >/dev/null 2>&1; then
    info "Starting Ollama service..."
    ollama serve &>/dev/null &
    OLLAMA_PID=$!
    # Wait for Ollama to be ready
    for i in $(seq 1 30); do
        if curl -s http://localhost:11434/api/tags >/dev/null 2>&1; then
            break
        fi
        sleep 1
    done
    if ! curl -s http://localhost:11434/api/tags >/dev/null 2>&1; then
        fail "Ollama failed to start after 30 seconds"
    fi
    ok "Ollama is running (PID ${OLLAMA_PID})"
fi

# ── Pull Ollama models ────────────────────────────────────────────────────
if [[ "$SKIP_OLLAMA" == false ]]; then
    info "Pulling Ollama models for ${PROFILE} profile..."

        # Read model names from profiles.json
        if [[ -f "${INSTALL_DIR}/profiles.json" ]]; then
            MANAGER_MODEL=$(jq -r ".${PROFILE}.manager" "${INSTALL_DIR}/profiles.json")
            FORENSICATOR_MODEL=$(jq -r ".${PROFILE}.forensicator" "${INSTALL_DIR}/profiles.json")
            CRITIC_MODEL=$(jq -r ".${PROFILE}.critic" "${INSTALL_DIR}/profiles.json")
        else
            # Fallback if profiles.json missing
            if [[ "$PROFILE" == "cloud" ]]; then
                MANAGER_MODEL="deepseek-v3.2:cloud"
                FORENSICATOR_MODEL="qwen3-coder-next:cloud"
                CRITIC_MODEL="qwen3.5:cloud"
            else
                MANAGER_MODEL="deepseek-r1:32b"
                FORENSICATOR_MODEL="qwen2.5-coder:14b"
                CRITIC_MODEL="qwen2.5:14b"
            fi
        fi

        info "  Manager:      ${MANAGER_MODEL}"
        info "  Forensicator: ${FORENSICATOR_MODEL}"
        info "  Critic:       ${CRITIC_MODEL}"

        ollama pull "$MANAGER_MODEL"      || warn "Failed to pull ${MANAGER_MODEL}"
        ollama pull "$FORENSICATOR_MODEL" || warn "Failed to pull ${FORENSICATOR_MODEL}"
        ollama pull "$CRITIC_MODEL"        || warn "Failed to pull ${CRITIC_MODEL}"

        ok "Models pulled"
else
    info "Skipping Ollama model pulls (--skip-ollama)"
fi

# ── Summary ─────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}╔══════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║          GEOFF Installation Complete             ║${NC}"
echo -e "${GREEN}╠══════════════════════════════════════════════════╣${NC}"
echo -e "${GREEN}║${NC} Profile:    ${YELLOW}${PROFILE}${NC}"
echo -e "${GREEN}║${NC} Directory:  ${INSTALL_DIR}${NC}"
echo -e "${GREEN}║${NC} Config:     ${INSTALL_DIR}/.env${NC}"
echo -e "${GREEN}╠══════════════════════════════════════════════════╣${NC}"
echo -e "${GREEN}║${NC} To start:                                       ${NC}"
echo -e "${GREEN}║${NC}   cd ${INSTALL_DIR}                               ${NC}"
echo -e "${GREEN}║${NC}   source venv/bin/activate                      ${NC}"
echo -e "${GREEN}║${NC}   export \$(cat .env | xargs)                    ${NC}"
echo -e "${GREEN}║${NC}   python3 src/geoff_integrated.py                ${NC}"
echo -e "${GREEN}╠══════════════════════════════════════════════════╣${NC}"
echo -e "${GREEN}║${NC} To switch profiles:                             ${NC}"
echo -e "${GREEN}║${NC}   Edit .env: GEOFF_PROFILE=cloud|local          ${NC}"
echo -e "${GREEN}║${NC}   Or: GEOFF_PROFILE=local python3 src/geoff_integrated.py${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════════════╝${NC}"